jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "hi"
      - webhook/notify:
          endpoint: 'https://heuristic-bose-c0d64f.netlify.app/.netlify/functions/hello'
    working_directory: ~/repo
orbs:
  webhook: eddiewebb/webhook@volatile
version: 2.1